groups:

  - name: Network_Alerts
    rules:
      - alert: High latency HTTP
        expr: avg_over_time(probe_http_duration_seconds[1m]) > 1
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: Blackbox probe slow HTTP (instance {{ $labels.instance }})
          description: "HTTP request took more than 1s\n on instance {{ $labels.instance }}  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: High latency ping
        expr: avg_over_time(probe_icmp_duration_seconds[1m]) > 1
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: Server has slow ping (instance {{ $labels.instance }})
          description: "Ping took more than 1s\n  on instance {{ $labels.instance }} VALUE = {{ $value }}\n  LABELS = {{ $labels }}"


      - alert: HTTP Status Error
        expr: avg_over_time(probe_http_status_code[1m]) != 200
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: HTTP status  (instance {{ $labels.instance }})
          description: "HTTP status code not 200\n on instance {{ $labels.instance }}  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"


      - alert: High TCP connection
        expr: sum(node_netstat_Tcp_CurrEstab) > 300
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: TCP connection status  (instance {{ $labels.instance }})
          description: "Experiencing high TCP demand  on instance {{ $labels.instance }} "

