---
- name: General setup
  hosts: all
  become: true
  roles:
    - role: general
      tags: general-setup

- name: setting up Redis cluster
  hosts: redis
  become: true
  roles:
    - role: redis_cluster
      tags: redis-setup


- name: Set up the monitoring stack
  hosts: monitoring
  become: true
  tasks:
    - name: Include monitoring roles
      include_role:
        name: "{{ item }}"
      loop:
        - $PWD/roles/victoria_metrics_setup_dockerized
      when: mode == 'monitoring'
