---
- name: General setup
  hosts: all
  become: true
  roles:
    - role: general
      tags: general-setup

- name: setting up Redis cluster
  hosts: redis
  become: true
  roles:
    - role: redis_cluster
      tags: redis-setup
