---
- name: setting up Redis cluster
  hosts: all
  become: true
  tasks:
    - name: Include variables
      include_vars: "all.yaml"

    - name: Setting the basis on all nodes
      include_role:
        name: "{{ item }}"
      with_items:
        - $PWD/roles/Pre_Setup
        - $PWD/roles/OS_Tuning
        - $PWD/roles/Install_Docker


    - name: Install and Configure Redis instances
      include_role:
        name: "{{ item }}"
      with_items:
        - $PWD/roles/Install_Redis
      when: mode == 'redis'



    - name: Init Redis cluster
      include_role:
        name: "{{ item }}"
      with_items:
        - $PWD/roles/Init_Cluster
      when: mode == 'redis' and init_cluster == 'true'


    - name: Deploy Node exporter on all nodes
      include_role:
        name: "{{ item }}"
      with_items:
        - $PWD/roles/Node_Exporter
      when: mode == 'monitoring'


    - name: Deploy Redis exporter on redis nodes
      include_role:
        name: "{{ item }}"
      with_items:
        - $PWD/roles/Redis_Exporter
      when: mode == 'redis'

    - name: Set up the monitoring stack
      include_role:
        name: "{{ item }}"
      with_items:
        - $PWD/roles/Victoria_Metrics
      when: mode == 'monitoring'



