---
- name: setting up Redis cluster
  hosts: all
  become: true
  tasks:
    - name: Include variables
      include_vars: "all.yaml"

    - name: Setting the basis on all nodes
      include_role:
        name: "{{ item }}"
      with_items:
        - $PWD/roles/pre_setup
        - $PWD/roles/redis_os_tuning
        - $PWD/roles/install_docker


    - name: Install and Configure Redis instances
      include_role:
        name: "{{ item }}"
      with_items:
        - $PWD/roles/redis_cluster_certificate_generation
        - $PWD/roles/redis_cluster_pre_setup
        - $PWD/roles/redis_cluster_setup_dockerized
      when: mode == 'redis'



    - name: Init Redis cluster
      include_role:
        name: "{{ item }}"
      with_items:
        - $PWD/roles/redis_cluster_initializing
      when: mode == 'redis' and init_cluster == 'true'


    - name: Deploy Node exporter on all nodes
      include_role:
        name: "{{ item }}"
      with_items:
        - $PWD/roles/node_exporter_setup_dockerized
      when: mode == 'monitoring'


    - name: Deploy Redis exporter on redis nodes
      include_role:
        name: "{{ item }}"
      with_items:
        - $PWD/roles/redis_exporter_setup_dockerized
      when: mode == 'redis'

    - name: Set up the monitoring stack
      include_role:
        name: "{{ item }}"
      with_items:
        - $PWD/roles/victoria_metrics_setup_dockerized
      when: mode == 'monitoring'



