---
- name: check connectivity
  ping:
    data: alive

- name: update and upgrade system
  apt:
    update_cache: yes
    upgrade: dist

- name: pull the required image for Redis Exporter
  docker_image:
    name: "{{ redis_exporter_base_image }}:{{ redis_exporter_version }}"
    source: pull


- name: Set the config file for Redis slave instances
  template:
    dest: "{{ redis_directory_base_path }}Redis/Exporter/Docker/docker-compose.yaml"
    src: templates/docker-compose-exporter.yaml.j2
    mode: "0777"


- name: Run the containers
  community.general.docker_compose:
    project_src: "{{ redis_directory_base_path }}Redis/Exporter/Docker/"
    pull: true
    recreate: never
    state: present
    restarted: false
    remove_orphans: no
    remove_volumes: false
